CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password TEXT NOT NULL,
  name VARCHAR(150) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('recruiter', 'super_admin')),
  business_unit VARCHAR(80) NOT NULL DEFAULT '',
  account_status VARCHAR(20) NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS business_unit VARCHAR(80) NOT NULL DEFAULT '';

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS account_status VARCHAR(20) NOT NULL DEFAULT 'active';

DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  SELECT conname INTO constraint_name
  FROM pg_constraint
  WHERE conrelid = 'users'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) LIKE '%role%';

  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE users DROP CONSTRAINT %I', constraint_name);
  END IF;
END $$;

UPDATE users SET role='super_admin' WHERE role='hg';
UPDATE users SET business_unit='Sarastya Insan Bertumbuh' WHERE role='recruiter' AND business_unit='';
UPDATE users SET account_status='active' WHERE role='super_admin';

ALTER TABLE users
  ADD CONSTRAINT users_role_check CHECK (role IN ('recruiter', 'super_admin'));

CREATE TABLE IF NOT EXISTS periods (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  year INTEGER NOT NULL CHECK (year BETWEEN 2000 AND 2200),
  status VARCHAR(20) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'closed')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS candidates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period_id INTEGER NOT NULL REFERENCES periods(id) ON DELETE CASCADE,
  name VARCHAR(150) NOT NULL,
  institution VARCHAR(200) NOT NULL,
  institution_type VARCHAR(20) NOT NULL DEFAULT 'university' CHECK (institution_type IN ('smk', 'university')),
  major VARCHAR(150) NOT NULL,
  interest VARCHAR(150) NOT NULL,
  business_unit VARCHAR(80) NOT NULL DEFAULT 'Sarastya Insan Bertumbuh' CHECK (business_unit IN ('Sarastya Insan Bertumbuh', 'Sarastya Technology Innovations', 'Sarastya Business Process', 'Appslings')),
  selection_status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (selection_status IN ('pending', 'accepted', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS selection_status VARCHAR(20) NOT NULL DEFAULT 'pending'
  CHECK (selection_status IN ('pending', 'accepted', 'rejected'));

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS institution_type VARCHAR(20) NOT NULL DEFAULT 'university';

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS business_unit VARCHAR(80) NOT NULL DEFAULT 'Sarastya Insan Bertumbuh';

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS cover_letter_file TEXT NOT NULL DEFAULT '';

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS cv_file TEXT NOT NULL DEFAULT '';

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS transcript_file TEXT NOT NULL DEFAULT '';

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS portfolio_file TEXT NOT NULL DEFAULT '';

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS photo_file TEXT NOT NULL DEFAULT '';

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS document_status VARCHAR(20) NOT NULL DEFAULT 'pending';

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS document_note TEXT NOT NULL DEFAULT '';

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS interview_video_url TEXT NOT NULL DEFAULT '';

ALTER TABLE candidates
  ADD COLUMN IF NOT EXISTS presentation_video_url TEXT NOT NULL DEFAULT '';

UPDATE candidates SET institution_type='smk'
WHERE UPPER(institution) LIKE '%SMK%';

CREATE TABLE IF NOT EXISTS criteria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(10) NOT NULL UNIQUE,
  name VARCHAR(200) NOT NULL,
  type VARCHAR(10) NOT NULL CHECK (type IN ('benefit', 'cost')),
  priority_order INTEGER NOT NULL,
  sj NUMERIC(8, 6) NOT NULL DEFAULT 0,
  weight NUMERIC(12, 10) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS subcriteria (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  criterion_id INTEGER NOT NULL REFERENCES criteria(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  score NUMERIC(4, 2) NOT NULL CHECK (score BETWEEN 1 AND 5)
);

CREATE TABLE IF NOT EXISTS candidate_scores (
  candidate_id INTEGER NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  criterion_id INTEGER NOT NULL REFERENCES criteria(id) ON DELETE CASCADE,
  score NUMERIC(4, 2) NOT NULL CHECK (score BETWEEN 1 AND 5),
  PRIMARY KEY (candidate_id, criterion_id)
);

CREATE TABLE IF NOT EXISTS swara_process_state (
  id SMALLINT PRIMARY KEY CHECK (id = 1),
  weights_ready BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO swara_process_state (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE INDEX IF NOT EXISTS candidates_period_id_idx ON candidates(period_id);
CREATE INDEX IF NOT EXISTS candidates_business_unit_idx ON candidates(business_unit);
CREATE INDEX IF NOT EXISTS subcriteria_criterion_id_idx ON subcriteria(criterion_id);
CREATE INDEX IF NOT EXISTS candidate_scores_criterion_id_idx ON candidate_scores(criterion_id);
